import fs from "node:fs";
import path from "node:path";

// The catalog/metadata feed (papers.jsonl) is generated by the harness (ADR-0003).
// Read it at build time from the repo root (the site runs from site/).
export interface PaperEntry {
  canonical_key: string;
  slug: string;
  title: string;
  authors: string[];
  year: number | null;
  venue: string | null;
  venue_tier: string | null;
  status: string | null;
  tags: string[];
  topic_groups: string[];
  triage_label: string | null;
  triage_confidence: string | null;
  read_status: string | null;
  score: number | null;
  latest_version: string | null;
  source_updated_at: string | null;
  summary_status: string | null;
  summary_path: string | null;
  source_link: string | null;
  abstract: string | null;
  milestone: { field?: string; era?: string; significance?: string } | null;
}

const FEED = path.resolve(process.cwd(), "..", "registry", "papers.jsonl");

export function loadCatalog(): PaperEntry[] {
  if (!fs.existsSync(FEED)) {
    throw new Error(
      `papers.jsonl not found at ${FEED}. Run \`python3 ../scripts/update_indexes.py\` ` +
        `(the predev/prebuild hook does this automatically).`,
    );
  }
  return fs
    .readFileSync(FEED, "utf-8")
    .split("\n")
    .filter(Boolean)
    .map((l) => JSON.parse(l) as PaperEntry);
}

// Map a paper's summary_path ("library/<slug>/vN/summary.md") to the content-collection
// entry id ("<slug>/vN/summary"), so the catalog can join to the rendered body.
export function summaryEntryId(summaryPath: string | null): string | null {
  if (!summaryPath) return null;
  return summaryPath
    .replace(/^library\//, "")
    .replace(/\.(md|mdx)$/, "");
}

// Distinct, sorted facet values across the catalog.
export function facets(papers: PaperEntry[]) {
  const uniq = (xs: (string | null)[]) =>
    Array.from(new Set(xs.filter((x): x is string => !!x))).sort();
  return {
    venues: uniq(papers.map((p) => p.venue)),
    years: Array.from(new Set(papers.map((p) => p.year).filter((y): y is number => !!y))).sort(
      (a, b) => b - a,
    ),
    tags: uniq(papers.flatMap((p) => p.tags)),
    topicGroups: uniq(papers.flatMap((p) => p.topic_groups)),
    triageLabels: ["MUST_READ", "READ_SOON", "SKIM", "TRACK_ONLY", "SKIP"],
  };
}
