#!/usr/bin/env python3
"""update_indexes.py — regenerate all derived indexes from authoritative YAML.

Deterministic: same library state always produces byte-identical indexes (stable
sort, no timestamps in body except an explicit generated-at header line).

Regenerates:
  registry/papers.jsonl                (flat machine-readable cache)
  indexes/INDEX.md                     (top-level dashboard)
  indexes/BY_DATE.md
  indexes/BY_TAG.md
  indexes/BY_VENUE.md
  indexes/MUST_READ.md
  indexes/RECENT_TRENDS.md
  registry/catalog.sqlite              (optional cache, if sqlite3 available)
"""
from __future__ import annotations

import argparse
from collections import defaultdict

import paperlib as pl

LABEL_ORDER = {l: i for i, l in enumerate(pl.TRIAGE_LABELS)}
GENERATED_NOTE = "<!-- generated by scripts/update_indexes.py — do not edit by hand -->"


def _latest_version(paper: dict) -> dict:
    vs = paper.get("versions") or []
    return vs[-1] if vs else {}


def _flat(paper: dict) -> dict:
    v = _latest_version(paper)
    venue = paper.get("venue") or {}
    user = paper.get("user") or {}
    # pull scoring from latest version metadata if present on disk
    score = None
    label = user.get("triage_label")
    pdir = pl.LIBRARY / paper.get("slug", "")
    vk = v.get("version_key")
    meta = {}
    if vk:
        meta = pl.load_yaml(pdir / vk / "metadata.yaml") or {}
        sc = meta.get("scoring") or {}
        score = sc.get("score")
        label = label or sc.get("label")
    source_link = (meta.get("source_url") or v.get("source_url")
                   or (paper.get("canonical_urls") or [None])[0])
    return {
        "canonical_key": paper.get("canonical_key"),
        "slug": paper.get("slug"),
        "title": paper.get("title"),
        "authors": paper.get("authors") or [],
        "year": paper.get("year"),
        "venue": venue.get("name"),
        "venue_tier": venue.get("tier"),
        "status": venue.get("status"),
        "tags": paper.get("tags") or [],
        "topic_groups": paper.get("topic_groups") or [],
        "triage_label": label,
        "triage_confidence": user.get("triage_confidence"),
        "read_status": user.get("read_status"),
        "score": score,
        "latest_version": vk,
        "fetched_at": v.get("fetched_at"),
        "source_updated_at": v.get("source_updated_at"),
        "summary_status": v.get("summary_status"),
        "pdf_path": v.get("pdf_path"),
        "summary_path": v.get("summary_path"),
        "ids": paper.get("primary_ids") or {},
        "milestone": paper.get("milestone"),
        "knowledge_concepts": paper.get("knowledge_concepts") or [],
        "abstract": meta.get("abstract") or None,
        "source_link": source_link,
    }


def _short_authors(authors: list[str], n: int = 3) -> str:
    if not authors:
        return "—"
    if len(authors) <= n:
        return ", ".join(authors)
    return ", ".join(authors[:n]) + f" +{len(authors) - n}"


def _link(f: dict) -> str:
    title = (f["title"] or "(untitled)").replace("|", "\\|")
    summary = f.get("summary_path")
    if summary:
        return f"[{title}](../{summary})"
    pdir = f"library/{f['slug']}/{f.get('latest_version') or ''}"
    return f"[{title}](../{pdir})"


def _row(f: dict) -> str:
    label = f.get("triage_label") or "—"
    score = f"{f['score']:.0f}" if isinstance(f.get("score"), (int, float)) else "—"
    venue = f.get("venue") or "—"
    yr = f.get("year") or "—"
    return (f"| {label} | {score} | {_link(f)} | {_short_authors(f['authors'])} "
            f"| {venue} | {yr} | {', '.join(f['tags'][:4]) or '—'} |")


TABLE_HEAD = ("| Label | Score | Title | Authors | Venue | Year | Tags |\n"
              "|---|---|---|---|---|---|---|")


def _sort_key(f: dict):
    return (LABEL_ORDER.get(f.get("triage_label"), 99),
            -(f.get("score") or 0),
            f.get("title") or "")


def build(write: bool = True) -> dict:
    papers = list(pl.iter_papers())
    flats = [_flat(p) for p in papers]
    flats.sort(key=_sort_key)

    # papers.jsonl
    if write:
        pl.write_jsonl(pl.PAPERS_JSONL, flats)

    counts = defaultdict(int)
    for f in flats:
        counts[f.get("triage_label") or "UNLABELED"] += 1

    # INDEX.md
    # Deterministic: no build timestamp in the body (see ADR-0003 / R-NF-2).
    index = [f"# Paper Library Index", "", GENERATED_NOTE, "",
             f"_{len(flats)} paper(s)_", "",
             "## Summary", ""]
    index.append("| Label | Count |")
    index.append("|---|---|")
    for lbl in pl.TRIAGE_LABELS + ["UNLABELED"]:
        if counts.get(lbl):
            index.append(f"| {lbl} | {counts[lbl]} |")
    index += ["", "## All papers (ranked)", "", TABLE_HEAD]
    index += [_row(f) for f in flats]
    index += ["", "## Sub-indexes", "",
              "- [By date](BY_DATE.md)", "- [By tag](BY_TAG.md)",
              "- [By venue](BY_VENUE.md)", "- [Must read](MUST_READ.md)",
              "- [Recent trends](RECENT_TRENDS.md)", "- [Milestones](MILESTONES.md)",
              "- [Knowledge base](../knowledge/INDEX.md)", ""]

    # BY_DATE.md
    by_date = defaultdict(list)
    for f in flats:
        d = (f.get("source_updated_at") or f.get("fetched_at") or "")[:10] or "unknown"
        by_date[d].append(f)
    date_md = ["# Papers by date", "", GENERATED_NOTE, ""]
    for d in sorted(by_date, reverse=True):
        date_md += [f"## {d}", "", TABLE_HEAD]
        date_md += [_row(f) for f in sorted(by_date[d], key=_sort_key)]
        date_md.append("")

    # BY_TAG.md
    by_tag = defaultdict(list)
    for f in flats:
        for t in (f["tags"] or ["untagged"]):
            by_tag[t].append(f)
    tag_md = ["# Papers by tag", "", GENERATED_NOTE, ""]
    for t in sorted(by_tag):
        tag_md += [f"## {t} ({len(by_tag[t])})", "", TABLE_HEAD]
        tag_md += [_row(f) for f in sorted(by_tag[t], key=_sort_key)]
        tag_md.append("")

    # BY_VENUE.md
    by_venue = defaultdict(list)
    for f in flats:
        by_venue[f.get("venue") or "Preprint/Unknown"].append(f)
    venue_md = ["# Papers by venue", "", GENERATED_NOTE, ""]
    for v in sorted(by_venue):
        venue_md += [f"## {v} ({len(by_venue[v])})", "", TABLE_HEAD]
        venue_md += [_row(f) for f in sorted(by_venue[v], key=_sort_key)]
        venue_md.append("")

    # MUST_READ.md
    must = [f for f in flats if f.get("triage_label") in ("MUST_READ", "READ_SOON")]
    must_md = ["# Must read / read soon", "", GENERATED_NOTE, "",
               f"_{len(must)} paper(s) flagged for deep reading._", "", TABLE_HEAD]
    must_md += [_row(f) for f in must]
    must_md.append("")

    # RECENT_TRENDS.md — group by topic_group x month
    trends = defaultdict(lambda: defaultdict(list))
    for f in flats:
        month = (f.get("source_updated_at") or f.get("fetched_at") or "")[:7] or "unknown"
        for g in (f["topic_groups"] or ["unsorted"]):
            trends[g][month].append(f)
    trend_md = ["# Recent trends", "", GENERATED_NOTE, "",
                "Emerging activity by topic group and month (most recent first).", ""]
    for g in sorted(trends):
        trend_md.append(f"## {g}")
        for month in sorted(trends[g], reverse=True):
            items = trends[g][month]
            top = sorted(items, key=_sort_key)[:5]
            titles = "; ".join((t["title"] or "")[:70] for t in top)
            trend_md.append(f"- **{month}** ({len(items)}): {titles}")
        trend_md.append("")

    # MILESTONES.md — landmark papers grouped by field, ordered emergence -> recent.
    era_order = {"emergence": 0, "foundational": 1, "expansion": 2, "recent": 3}
    ms = [f for f in flats if f.get("milestone")]
    by_field = defaultdict(list)
    for f in ms:
        by_field[f["milestone"].get("field", "unsorted")].append(f)
    ms_md = ["# Milestone papers", "", GENERATED_NOTE, "",
             f"_{len(ms)} milestone paper(s) across {len(by_field)} field(s)._", "",
             "Landmark papers per field from emergence to recent. Curated in "
             "`config/milestones.yaml`; add more via /milestone-papers.", ""]
    for field in sorted(by_field):
        items = sorted(by_field[field], key=lambda f: (
            era_order.get(f["milestone"].get("era"), 9), f.get("year") or 0))
        ms_md += [f"## {field} ({len(items)})", "",
                  "| Era | Year | Title | Venue | Significance |",
                  "|---|---|---|---|---|"]
        for f in items:
            m = f["milestone"]
            sig = (m.get("significance") or "").replace("|", "\\|")
            ms_md.append(f"| {m.get('era','—')} | {f.get('year') or '—'} | {_link(f)} "
                         f"| {f.get('venue') or '—'} | {sig} |")
        ms_md.append("")

    outputs = {
        pl.INDEXES / "INDEX.md": "\n".join(index),
        pl.INDEXES / "BY_DATE.md": "\n".join(date_md),
        pl.INDEXES / "BY_TAG.md": "\n".join(tag_md),
        pl.INDEXES / "BY_VENUE.md": "\n".join(venue_md),
        pl.INDEXES / "MUST_READ.md": "\n".join(must_md),
        pl.INDEXES / "RECENT_TRENDS.md": "\n".join(trend_md),
        pl.INDEXES / "MILESTONES.md": "\n".join(ms_md),
    }
    if write:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content + "\n", encoding="utf-8")
        _maybe_sqlite(flats)

    return {"papers": len(flats), "counts": dict(counts)}


def _maybe_sqlite(flats: list[dict]) -> None:
    try:
        import sqlite3
    except ImportError:
        return
    con = sqlite3.connect(pl.CATALOG_SQLITE)
    try:
        con.execute("DROP TABLE IF EXISTS papers")
        con.execute("""CREATE TABLE papers (
            canonical_key TEXT PRIMARY KEY, slug TEXT, title TEXT, authors TEXT,
            year INTEGER, venue TEXT, venue_tier TEXT, status TEXT, tags TEXT,
            topic_groups TEXT, triage_label TEXT, score REAL, read_status TEXT,
            latest_version TEXT, fetched_at TEXT, source_updated_at TEXT,
            summary_status TEXT, pdf_path TEXT, summary_path TEXT)""")
        for f in flats:
            con.execute(
                "INSERT OR REPLACE INTO papers VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (f["canonical_key"], f["slug"], f["title"], "; ".join(f["authors"]),
                 f["year"], f["venue"], f["venue_tier"], f["status"],
                 ", ".join(f["tags"]), ", ".join(f["topic_groups"]),
                 f["triage_label"], f["score"], f["read_status"], f["latest_version"],
                 f["fetched_at"], f["source_updated_at"], f["summary_status"],
                 f["pdf_path"], f["summary_path"]))
        con.commit()
    finally:
        con.close()


def _main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate derived indexes.")
    ap.add_argument("--dry-run", action="store_true", help="compute but do not write")
    args = ap.parse_args()
    res = build(write=not args.dry_run)
    print(f"indexes {'(dry-run) ' if args.dry_run else ''}rebuilt: "
          f"{res['papers']} paper(s) {res['counts']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
